### ISSUE TITLE
cross compilation failing on linux due to -lMsimg32 not found

### ISSUE THREAD

**Issue by hemantmits** [noodle1983/putty-nd#1]
Hi ,

First thanks for your great efforts putty-nd :).

I have one small issue while cross compiling putty-nd on linux for Windows. in Recipe file

_Recipe:         + shell32.lib winmm.lib imm32.lib winspool.lib ole32.lib *_Msimg32.lib***

due to capital "m" in  Msimg32.lib name ld is not able to find Msimg32.lib library on file system. 
After I made it  msimg32.lib it worked fine.

It would be great if you can fix it in your repository as well.

Thanks & Regards,
Hemant

**Comment by noodle1983** [comment]
cross compiling? for arm?
ok, piece of cake.
