### ISSUE TITLE
change tab names

### ISSUE THREAD

**Issue by pushb** [noodle1983/putty-nd#10]
can you add the facility to add name to the tabs. i want to name my tabs as coding, testing, 14.23 testing, etc..

Is it possible to add this feature in your backlog?

**Comment by noodle1983** [comment]
I guess this is what you want, try Ctrl + Shift + e.

**Comment by pushb** [comment]
Thanks it worked.

**Comment by pushb** [comment]
instead of keyboard shortcut, is it possible to add a new facility in the right click of tab that can show **rename** option.
