### ISSUE TITLE
ctrl+tab / ctrl+shift+tab not working properly

### ISSUE THREAD

**Issue by ghost** [noodle1983/putty-nd#3]
latest releast 2014-01-03 has problem with tab changing. It used to work that ctrl+tab goes to next tab and ctrl+shift+tab goes to previous tab. Now all it does, is that it goes to previous tab with both key combinations

**Comment by noodle1983** [comment]
Close as it is configurable now in putty-nd6.4.

**Comment by ghost** [comment]
Haven't been using anykind of putty for years anymore :). I'll take your word for it.
