### ISSUE TITLE
Extend selection doesn't work.

### ISSUE THREAD

**Issue by Enochsoul** [noodle1983/putty-nd#8]
Version 6.4
I normally use middle-click to extend, doesn't work in 6.4.  Changing config to right-click to extend, still doesn't work.
Configuration the same as a original PuTTY, but works there.

Thanks for your work on this, saves my desktop from putty window clutter.

**Comment by noodle1983** [comment]
Hi,  Enochsoul， Thanks for the report. Please try the attachment, it will be released in the next version if everything is fine.
[putty.exe.bak.zip](https://github.com/noodle1983/putty-nd/files/2609635/putty.exe.bak.zip)

**Comment by Enochsoul** [comment]
That resolved the problem.
