### ISSUE TITLE
Tabs not showing

### ISSUE THREAD

**Issue by Dinip** [noodle1983/putty-nd#9]
Hi,
Since last week the opened tabs are not showing up 
![image](https://user-images.githubusercontent.com/8941012/48980985-e838e100-f0c7-11e8-88e2-fe4a540e0e28.png)

**Comment by noodle1983** [comment]
I tried to reproduce the issue these days but with no luck.
May I know the OS version? And the release number if possible?

**Comment by Dinip** [comment]
I think it is the latest version available. This is only happening on this computer with this version. On my other computers the tabs are showing up. Maybe an issue with this version of windows? 
Windows 10
Version 1809
OS build 17763.134

**Comment by noodle1983** [comment]
Hi there, I believe it is the issue with the window10 native theme. So I disabled it. Would you please help to verify if it fixed the issue?
download link: https://sourceforge.net/p/putty-nd/bugs/_discuss/thread/9f9276740a/5d15/attachment/putty.exe.zip

**Comment by Dinip** [comment]
yep it did fixed the issue! So is it supposed to keep this .exe?
![image](https://user-images.githubusercontent.com/8941012/49297236-38da8080-f4b2-11e8-9e93-50d62d44f23c.png)

**Comment by noodle1983** [comment]
Thanks, and yes, it will be released in the next version.
